/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommonTitle: typeof import('./../components/common-title/index.vue')['default']
    LoadMore: typeof import('./../components/load-more/index.vue')['default']
    MyImg: typeof import('./../components/my-img/index.vue')['default']
    NavBar: typeof import('./../components/nav-bar/index.vue')['default']
    Reload: typeof import('./../components/reload/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollTags: typeof import('./../components/scroll-tags/index.vue')['default']
    TabBar: typeof import('./../components/tab-bar/index.vue')['default']
    ThemeSwitch: typeof import('./../components/theme-switch/index.vue')['default']
  }
}
